<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" >
  <meta name="viewport" content="width=device-width, initial-scale=1.0">  
  <title>例外処理の例</title>
</head>
<body>
  <script>
    function f() {
      return x;
    }
    try {
      const v = f a();
      document.write(`f()から返ってきた値は${v}です`);
    }
    catch (error) {
      document.write("エラーが発生したので、処理を中断しました。<br>");
      document.write(`エラーメッセージは次のとおりです:「${error.message}」`);
    }
  </script>
</body>
</html>
